### ISSUE TITLE
slog relative pathname handling is inconsistent with standard functions

### ISSUE THREAD

**Issue by goose121** [tfeb/tfeb-lisp-hax#3]
In the documentation for `slog`, it is stated explicitly that the process's working directory is used for log files, and that the portable fallback `(make-pathname :name nil :type nil :version nil :defaults *default-pathname-defaults*)` is almost certainly wrong.

However, this means that the method `slog` uses to resolve relative pathnames is different from the method used by all functions defined in the CL standard, which are [defined](http://clhs.lisp.se/Body/19_bc.htm) to merge all pathnames with `*default-pathname-defaults*` before filesystem access (additionally, setting certain components of `*default-pathname-defaults*` to `nil` before performing merging is not in the specification, should generally be unnecessary, and further deviates from the standard procedure).

In the standard, [it is stated](http://clhs.lisp.se/Body/v_defaul.htm) that `*default-pathname-defaults*` is "typically in the working directory that was current when Common Lisp was started up", so in general the behaviour of `slog` would not change for most programs if the merging was done with respect to `*default-pathname-defaults*`, unless they change their working directory with `chdir` without also updating `*default-pathname-defaults*` (which is somewhat of an unusual thing to do, in my opinion, and also makes the standard functions behave in a surprising way and so is generally avoided), and may be surprising if, for instance, a user binds `*default-pathname-defaults*` lexically and expects files which were being placed in the current directory to be placed elsewhere.

Additionally, the pathname canonicalization function should probably call [`translate-logical-pathname`](http://clhs.lisp.se/Body/f_tr_log.htm) on the input before merging. This allows using logical pathnames, which could be very useful for logging (e.g. a client could define a logical pathname host called `log`, set to the platform-appropriate logging location, and then specify its log-file paths as `log:foo.log` `log:bar;baz.log` etc.), and also lines up better with the behaviour of `open` and other standard filesystem functions, which also perform logical pathname translations.

I am willing to create a pull request implementing these behaviours, if desired; I submitted an issue first to gauge opinion on this.

EDIT: actually, it *is* possible to use logical pathnames in the current state; the issue is that, without translating them, a logical pathname will have a different stream than its equivalent, translated, physical pathname, as follows:
```
CL-USER> (setf (logical-pathname-translations "log") '(("**;*.*.*" "/var/log/**/")))
(("**;*.*.*" "/var/log/**/"))
CL-USER> (org.tfeb.hax.slog:slog-to "log:foo;bar.log" "test1")
#<ORG.TFEB.HAX.SLOG:SIMPLE-LOG-ENTRY "test1" {10081F14A3}>
CL-USER> (org.tfeb.hax.slog:slog-to "/var/log/foo/bar.log" "test2~%")
#<ORG.TFEB.HAX.SLOG:SIMPLE-LOG-ENTRY "test2~%" {100820A1D3}>
CL-USER> (org.tfeb.hax.slog:flush-open-log-file-streams)
(#P"/var/log/foo/bar.log" #P"LOG:FOO;BAR.LOG")
```
Note that in this example "/var/log/foo/bar.log" and "log:foo;bar.log" point to the same file.

**Comment by tfeb** [comment]
@goose121 thanks for this.  You are right about logical pathnames: they work but I didn't think about them in the implementation and I need to think about them some more (this is a dumb mistake because I use logical pathnames really a lot, and they're an obvious match for logging destinations).

For the `*default-pathname-defaults*` / current working directory thing.  The problem here is that there is a choice between doing the right thing and actually working reasonably well.  The right thing is simply using `*default-pathname-defaults*`, clearly.  But for the right thing to work, the value of that needs to correspond to the current working directory, which means that whatever (ultimately implementation-defined) method is used to change working directory also needs to set `*default-pathname-defaults*` and, worse, something like this needs to work:

```lisp
(progn
  (let ((*default-pathname-defaults* *default-pathname-defaults*))
    ... change directory, also changing *default-pathname-defaults* ...
    ... code in new directory ...)
  ... code in *old* directory ...)
```

It is extremely unlikely that anything like this could be made to work in any implementation which sits on a platform (like Unixoid systems) where there is a notion of a current working directory for a process, without treating `*default-pathname-defaults*` in some completely magic way.

But it's worse even than that: the interfaces that actually exist to change working directory (for instance `uiop:chdir`) *don't set* `*default-pathname-defaults*` anyway, so everything is completely hopeless before you even start.

So there are two choices:

- listen to `*default-pathname-defaults*` (the right thing) ...
- ... or respect the current process working directory in any implementation I  have tried (which is, pretty much, SBCL, LW, CCL, and anything with ASDF).

You can't do both, and I've taken the latter choice, because I think it's much closer to being useful.

*However* all is not lost.  The underlying problem here is that what the system needs to know is the truename of a file *which may not yet exist* and which it does not want to open or create.  Well, that can be fixed easily: just open the wretched file, creating it if need be.  So if it opens log files at the point they're first mentioned (so, usually in the expansion of `logging` macro), rather than at the moment a handler first wants to write to that file, the truename is then known, and none of this fanciness is needed.

And that's better in other ways, too, as it means that if the file can't in fact be opened you get the error at a much better time and in particular *not* when the first event which ends up wanting to write to the file happens, which is a very bad time.

So I'm probably going to modify `slog` (incompatibly) to do that, which will make this entire issue go away I think.  If I don't do that, then the documentation needs to be changed to add the rationale for why it does what it does.

I will leave this open until then.

**Comment by tfeb** [comment]
@goose121 PS if you're happy to check the new version that would be cool.  It will likely take me some days depending.

**Comment by goose121** [comment]
I would be happy to check the new version; I think this is an interesting project and I'd like to do what I can to help it flourish.

I think it might be informative to see what other CL software does with regards to `*default-pathname-defaults*`; from what little I've seen in in CL, most software I've seen that works with relative pathnames completely ignores Unix's version of working directories (thus making it behave consistently within the ecosystem, even if it doesn't behave consistently with how most other Unix software works). From what I have seen the right thing is different in Common Lisp than in other software; it seems that Unix's idea of "current directory" is what would be considered "surprising"  because users generally set their current directory with `(setf *default-pathname-defaults*)` due to the fact that this is the one which affects most built-in Lisp functions, and `chdir` seems to be reserved for FFI and for ensuring child processes are spawned with the right pwd. IMO, it would be surprising if I changed my working directory for CL but specifically the logging library didn't also change its idea of where to put files.

Admittedly, I haven't seen much code dealing with this at all (I don't see a lot of CL software that deals explicitly with the working directory; usually it just lets `open` and such handle that), so further research may be needed.

P.S. even treating `*default-pathname-defaults*` in a magic way probably wouldn't work, as the value of a special variable is supposed to be local to a thread, while the working directory is global within a process; I think this is also part of the reason why `*default-pathname-defaults*` tends to be used over `chdir` in CL programs

P.P.S. UIOP's `with-current-directory` does actually set both; I think chdir is defined the way it is so as to be a low-level tool

**Comment by tfeb** [comment]
@goose121 Thank you.  I have a new version which now does no pathname magic at all: the only thing it does is call `pathname` to turn strings into pathnames.  It is potentially slower in some cases than the old one if you treat it badly and I've currently tried it only on a single implementation/platform.  Most importantly I need to rewrite the README as various things are pretty different.  I'll probably not have time to do that before early next week.  I'll commit it on a branch then and let you know.

**Comment by tfeb** [comment]
@goose121 have a look at the [`slog-pathname-minimality`](https://github.com/tfeb/tfeb-lisp-hax/tree/slog-pathname-minimality) branch.  This has a new version of `slog` which does not have this problem but which may be buggy still.  The README is at least mostly correct for it.

I probably will not be able to look at this again until next week.

**Comment by tfeb** [comment]
I am closing this against 22361884d15e8c013a5df7f7596f63dfeb7ac62d, which I've just merged: this version of `slog` may have bugs, but it does no longer do anything unconventional with directories, and I needed to merge the branch.

If it's clearly still broken either reopen this or make a new issue.

**Comment by goose121** [comment]
looks good! sorry for the lack of response

**Comment by tfeb** [comment]
@goose121 no problem, sorry if my comment made it sound like I expected you to have done work which I wasn't: I was just needing to merge it while I could still fast-forward it...
